name: OneHitKill
main: _64FF00\OneHitKill\OneHitKill
version: "1.0.0"
api: [1.9.0]
load: STARTUP
author: 64FF00
website: https://github.com/64FF00/OneHitKill
commands:
  ohk:
    description: "Allows you to kill players in one hit."
    permission: ohk.main
permissions: 
  ohk:
    description: "#64FF00"
    children:
      ohk.main:
        description: "Allows you to kill players in one hit."